name: fitodelizacion_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Dependencias Firebase
  firebase_storage: ^11.0.15
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.4.0
  #Dependencia para iconos
  flutter_launcher_icons: ^0.10.0
  

flutter_icons:
  image_path: "static/coffe-cup.png"
  android: true 
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - static/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
